import type { AppState, AvailabilitySlot, Beat, Settings } from "../types";
import { addDays, getTimeSlots, normalizeWeekStart } from "../utils/time";

const todayMonday = normalizeWeekStart(new Date().toISOString().slice(0, 10));

const actors = [
  { id: "actor_ava", name: "Ava Stone", email: "ava@example.com", notes: "Hamlet cover", active: true },
  { id: "actor_miles", name: "Miles Reed", email: "miles@example.com", notes: "Fight captain", active: true },
  { id: "actor_june", name: "June Park", email: "june@example.com", notes: "", active: true },
  { id: "actor_sam", name: "Sam Rivera", email: "sam@example.com", notes: "", active: true },
  { id: "actor_noor", name: "Noor Patel", email: "noor@example.com", notes: "Music lead", active: true },
  { id: "actor_eli", name: "Eli Chen", email: "eli@example.com", notes: "", active: true },
  { id: "actor_tess", name: "Tess Morgan", email: "tess@example.com", notes: "", active: true },
  { id: "actor_omar", name: "Omar Blake", email: "omar@example.com", notes: "", active: true },
];

const settings: Settings = {
  playTitle: "Hamlet",
  rehearsalStartTime: "15:00",
  rehearsalEndTime: "18:00",
  plannerSlotMinutes: 10,
  availabilityBlockMinutes: 30,
  maxAbsencesAllowed: 0,
  maxParallelBlocks: 2,
  lanes: ["Main", "Second"],
  weekStartDate: todayMonday,
  scheduleExportFormat: "director",
  scheduleExportIncludeActors: true,
  scheduleExportIncludeCharacters: true,
  scheduleExportIncludeConflicts: true,
  scheduleDesign: {
    template: "beatCardsByDay",
    customDesignName: "My schedule format",
    renderMode: "beatCardsByDay",
    primaryColor: "#15231f",
    accentColor: "#426d5a",
    sceneColor: "#5f86a6",
    fightColor: "#c7624f",
    musicColor: "#7c5fa6",
    runColor: "#5f8f63",
    useRehearsalTypeColors: true,
    fontPairing: "classic",
    blockStyle: "rounded",
    density: 58,
    showActorNames: true,
    showCharacterNames: true,
    showRoom: true,
    showConflicts: true,
    showNotes: true,
    showIcons: true,
    showDurations: true,
    showLaneNames: true,
    showRehearsalNumbers: false,
    headerStyle: "ribbon",
    headerLabel: "Weekly Rehearsal Schedule",
    logoPosition: "topRight",
    logoSize: 48,
    directorName: "",
    directorContact: "",
    directorContactPlacement: "none",
    rehearsalNotes: "Bring scripts, pencils, and water.",
    emergencyContact: "Stage manager: 555-0142",
    footerText: "Generated by Rehearsal Scheduler",
    timeFormat: "12",
    layout: "cards",
    paperSize: "letter",
    orientation: "landscape",
    spacing: "comfortable",
    paginationMode: "preferOnePage",
    fitBehaviorVersion: 4,
    designSystemVersion: 3,
    minimumTextSize: 11,
    timeTextAlign: "left",
    workTextAlign: "left",
    actorTextAlign: "left",
    cellContentVerticalAlign: "top",
    boldTimes: true,
    boldWork: true,
    boldActorNames: false,
    cardTimePlacement: "top",
    calledLabel: "Called",
    roomLabel: "Room",
    charactersLabel: "Characters",
    notesLabel: "Notes",
    conflictsLabel: "Conflicts",
    weekLabel: "Week of",
    timeLabel: "Time",
    workLabel: "Work",
    actorsLabel: "Actors",
    keepDaysTogether: true,
    avoidSplittingBlocks: true,
    customLayoutEnabled: false,
    customPageCount: 1,
    customCanvasZoom: 100,
    snapToGrid: true,
    customShowBlockCards: true,
    customScheduleStyle: "table",
    customBlockLayouts: {},
    customCells: [],
  },
};

const beats: Beat[] = [
  { id: "beat_all", title: "All", rosterActorIds: actors.map((actor) => actor.id), notes: "Full cast", targetRehearsalCount: 3 },
  { id: "beat_1", title: "Act 1 Opening", rosterActorIds: ["actor_ava", "actor_miles", "actor_june", "actor_sam"], targetRehearsalCount: 3 },
  { id: "beat_2", title: "Scene 3 Discovery", rosterActorIds: ["actor_ava", "actor_noor", "actor_eli"], targetRehearsalCount: 3 },
  { id: "beat_3", title: "Fight Call", rosterActorIds: ["actor_miles", "actor_sam", "actor_omar"], targetRehearsalCount: 3 },
  { id: "beat_4", title: "Music", rosterActorIds: ["actor_noor", "actor_tess", "actor_june"], targetRehearsalCount: 3 },
  { id: "beat_5", title: "Final Image", rosterActorIds: ["actor_ava", "actor_miles", "actor_noor", "actor_tess", "actor_omar"], targetRehearsalCount: 3 },
];

function buildAvailability(): AvailabilitySlot[] {
  const slots: AvailabilitySlot[] = [];
  const times = getTimeSlots(settings.rehearsalStartTime, settings.rehearsalEndTime, settings.availabilityBlockMinutes);
  for (const actor of actors) {
    for (const dayOfWeek of [1, 2, 3, 4, 5] as const) {
      for (const startTime of times) {
        const available =
          !(actor.id === "actor_tess" && dayOfWeek === 2 && startTime < "16:30") &&
          !(actor.id === "actor_eli" && dayOfWeek === 4 && startTime >= "17:00") &&
          !(actor.id === "actor_omar" && dayOfWeek === 1 && startTime === "15:00");
        slots.push({
          actorId: actor.id,
          dayOfWeek,
          startTime,
          endTime: getTimeSlots(startTime, "23:59", settings.availabilityBlockMinutes)[1] ?? startTime,
          available,
        });
      }
    }
  }
  return slots.map((slot) => {
    const [h, m] = slot.startTime.split(":").map(Number);
    const total = h * 60 + m + settings.availabilityBlockMinutes;
    return { ...slot, endTime: `${String(Math.floor(total / 60)).padStart(2, "0")}:${String(total % 60).padStart(2, "0")}` };
  });
}

export const demoState: AppState = {
  actors,
  actorGroups: [
    { id: "group_mechanicals", name: "Mechanicals", actorIds: ["actor_miles", "actor_sam", "actor_omar"], notes: "Comedy / physical work" },
    { id: "group_royal", name: "Court", actorIds: ["actor_ava", "actor_noor", "actor_eli", "actor_tess"], notes: "Palace scenes" },
  ],
  availability: buildAvailability(),
  beats,
  characterMap: [
    { actorId: "actor_ava", characterName: "Hamlet" },
    { actorId: "actor_miles", characterName: "Laertes" },
    { actorId: "actor_june", characterName: "Ophelia" },
    { actorId: "actor_sam", characterName: "Horatio" },
    { actorId: "actor_noor", characterName: "Gertrude" },
    { actorId: "actor_eli", characterName: "Claudius" },
    { actorId: "actor_tess", characterName: "Ghost" },
    { actorId: "actor_omar", characterName: "Player King" },
  ],
  overrides: [
    { id: "ov_1", actorId: "actor_ava", date: addDays(todayMonday, 2), startTime: "16:00", endTime: "16:40", type: "unavailable", notes: "Callback" },
    { id: "ov_2", actorId: "actor_miles", date: addDays(todayMonday, 0), startTime: "17:00", endTime: "18:00", type: "unavailable", notes: "Class" },
    { id: "ov_3", actorId: "actor_tess", date: addDays(todayMonday, 3), startTime: "15:30", endTime: "16:00", type: "available", notes: "Can arrive early this day" },
  ],
  plannerBlockouts: [
    { id: "blockout_lunch", date: todayMonday, startTime: "16:30", endTime: "16:50", type: "break", title: "Company break", actorIds: actors.map((actor) => actor.id), includeInSchedule: true },
  ],
  plannerSelections: [
    { date: todayMonday, startTime: "15:10", laneId: "Main", beatId: "beat_1" },
    { date: todayMonday, startTime: "15:20", laneId: "Main", beatId: "beat_1" },
    { date: todayMonday, startTime: "15:30", laneId: "Main", beatId: "beat_1" },
    { date: addDays(todayMonday, 1), startTime: "16:00", laneId: "Second", beatId: "beat_4" },
    { date: addDays(todayMonday, 1), startTime: "16:10", laneId: "Second", beatId: "beat_4" },
  ],
  scheduledBlocks: [],
  scheduleLog: [],
  settings,
};
